# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.6

install: composer update

before_script:
- composer self-update
- composer install
- composer dump-autoload

script: php bin/codecept.phar run

notifications:
    on_success: always
    on_failure: always